---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	planificador(planificador)
	extraccion(extraccion)
	rag(rag)
	contraste(contraste)
	validador(validador)
	generador(generador)
	__end__([<p>__end__</p>]):::last
	__start__ --> planificador;
	contraste --> validador;
	extraccion --> contraste;
	planificador --> extraccion;
	planificador --> rag;
	rag --> contraste;
	validador --> generador;
	generador --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
